### ISSUE TITLE
Question, where is the build script?

### ISSUE THREAD

**Issue by cmabastar** [karec/cookiecutter-flask-restful#13]
I tried to download the code but there seems to be no script to run the bootstrap. Do i need to get from https://github.com/sloria/cookiecutter-flask `tasks.py` ?

**Comment by karec** [comment]
you need to use cookiecutter to actually render the code, you can get it here https://github.com/audreyr/cookiecutter or use pip to install it `pip install cookiecutter`

Then you just need to run 

```cookiecutter gh:karec/cookiecutter-flask-restful
```
Or if you already cloned to repo 

```
cookiecutter path/to/cookiecutter-flask-restful
```
