### ISSUE TITLE
method_decorator unused?

### ISSUE THREAD

**Issue by joshuar500** [karec/cookiecutter-flask-restful#15]
first, just wanna say thank you for making this project.

i noticed that `method_decorator` is assigned `[jwt_required]` but it isn't used? not sure if i'm reading it correctly, but maybe it belongs above the `put` and `delete` requests as `@method_decorator` by default? or is it up to the user to decide...

**Comment by karec** [comment]
Hi @joshuar500 

`method_decorator` comes from flask-restFul itself (https://flask-restful.readthedocs.io/en/0.3.5/extending.html#resource-method-decorators), it's used to apply decorators to all methods of the resource.

A good thing to know is that if you want to apply this decorator only to some methods (for example like you said on `put` and `delete` requests only), you can use a mapping like this:

```python
method_decorators = {
    "put": [jwt_required],
    "delete": [jwt_required]
}
```

You can see how this property is used in flask-restFul's source code here: https://github.com/flask-restful/flask-restful/blob/master/flask_restful/__init__.py#L572

Hope this has answered your question !

**Comment by joshuar500** [comment]
Awesome! Thank you very much!
