### ISSUE TITLE
Wrong Client Method

### ISSUE THREAD

**Issue by M0r13n** [karec/cookiecutter-flask-restful#16]
https://github.com/karec/cookiecutter-flask-restful/blob/b1f5b5e006a0a3d17d347a5b2e2fb74541652e79/%7B%7Bcookiecutter.project_name%7D%7D/tests/test_user.py#L62

Shouldn't this be client.delete instead of client.put

**Comment by karec** [comment]
You're right, thanks for the report, fix incoming
