### ISSUE TITLE
Separate Schema and Ressources in separates modules

### ISSUE THREAD

**Issue by espoirMur** [karec/cookiecutter-flask-restful#34]
Bonjour @karec !

What do you think about separating resources and schemas and have them in 2 different packages?

Why I have an impression that having this in one module violates the Single responsibility principle or separation of concern? But I am not sure, maybe you can give some light on this.

Plus it may increase readability for the cookiecutter.

What are your thoughts? 

I can work on this if you agree.

**Comment by karec** [comment]
Fixed in #35
