### ISSUE TITLE
Make the project PEP8 compliant...

### ISSUE THREAD

**Issue by espoirMur** [karec/cookiecutter-flask-restful#36]
TODOS: to be updated

**Comment by karec** [comment]
Do you have an example for this one ? The only thing that comes to my mind is the line-length rule, but this is set in `tox.ini` and can be easily changed and last travis build was successful including black + flake8: https://travis-ci.org/github/karec/cookiecutter-flask-restful/jobs/683013394

**Comment by karec** [comment]
This issue hasn't been active since some months, I'm closing it for now but feel free to re-open it if needed
