### ISSUE TITLE
Currently broken because incompatable with Celery 5

### ISSUE THREAD

**Issue by kbrown** [karec/cookiecutter-flask-restful#44]
Installs latest Celery and then...

celery_1    | You are using `-A` as an option of the worker sub-command:
celery_1    | celery worker -A celeryapp <...>
celery_1    | 
celery_1    | The support for this usage was removed in Celery 5.0. Instead you should use `-A` as a global option:
celery_1    | celery -A celeryapp worker <...>
celery_1    | Usage: celery worker [OPTIONS]
celery_1    | Try 'celery worker --help' for help.
celery_1    |

**Comment by karec** [comment]
Hello @kbrown and thanks for reporting this.

I will work on this as soon as I can to fix this and ensure everything else works fine with celery 5

**Comment by karec** [comment]
Fixed with 783746e3a79d4dab6a3bed9713b07a0557dd82f0
