### ISSUE TITLE
Flask 2.0 just came out and broke all :(

### ISSUE THREAD

**Issue by jayrod** [karec/cookiecutter-flask-restful#51]
I had to downgrade to Flask 1.1.2 and all seems good with the world again. Perhaps a change to the requirements.txt until a fix can be made?

**Comment by karec** [comment]
Hello @jayrod, thanks for reporting the issue and sorry that I have took so much time to answer. I'll dive into the issue, if fixing everything for flask 2.0 take too much time I will indeed fix the requirements.txt until I can work on a proper PR

**Comment by caffeinatedMike** [comment]
Hey @jayrod and @karec I've opened a PR that addresses the CLI issue for Flask 2.0. It also updates Swagger UI and added an alternative UI ([ReDoc](https://github.com/Redocly/redoc)) that works alongside Swagger UI (for a professional, read-only API overview). Thanks to `APISpec`, all that needed to be done was add an extra route that returned the YAML version of the spec.

**Comment by karec** [comment]
Hi @caffeinatedMike and thank you a lot for this PR, I've merged it.
